### ISSUE TITLE
Zero down time/rolling updates with Quarkus

### ISSUE THREAD

**Issue by iabughosh** [quarkusio/quarkus-quickstarts#1034]
I have a service which runs on Quarkus 2.6.0.Final. My goal here is to achieve zero down time deployment using rolling update strategy. My service has CORS filter and micro-profile health plugin enabled and when I update my deployment image to a newer version while there is an active user, browser logs give the below message : 

> "Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at xxx. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 503."

while xxx is my service endpoint.

My conclusion here is that q/health/ready endpoint return 200 while CORS setup & filter for that service is not started yet!

Here is my environment/service details :
- OpenJDK 17
- Podman 3.2.1
- Openshift 4.9.10
- Quarkus 2.6.0
- 2 pods are running for this service (Even if it is increased to 3 result is the same)
- CORS & microprofile health are enabled
- Deployment has liveness & readiness probes which points to live & ready endpoints.

**Comment by iabughosh** [comment]
Moved issue to right repository.

**Comment by ozkanpakdil** [comment]
I was looking for same thing, which repository ?
