### ISSUE TITLE
Path to class wrong in jwt quickstart guide

### ISSUE THREAD

**Issue by vanalex** [quarkusio/quarkus-quickstarts#1069]
Hi,

following the quickstart guide https://quarkus.io/guides/security-jwt, there is a wrong path.

wrong => security-jwt-quickstart/src/**main**/java/org/acme/security/jwt/GenerateToken.java

I think it should be

right => security-jwt-quickstart/src/**test**/java/org/acme/security/jwt/GenerateToken.java

according to the example provided.

Many thanks and have a great day.

**Comment by sberyozkin** [comment]
@vanalex Thanks for opening this issue, sorry I've missed it. I'll fix it, but if you'd like you can open a tiny PR in the main Quarkus repository against this file, https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/security-jwt.adoc

**Comment by sberyozkin** [comment]
Fixed with https://github.com/quarkusio/quarkus/pull/25267
