### ISSUE TITLE
org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)

### ISSUE THREAD

**Issue by kbntk** [quarkusio/quarkus-quickstarts#1088]
When I'm trying to query the kafka server using e.g. firefox I get following error and stack trace: 

` [2022-03-21 13:19:45,515] WARN [SocketServer brokerId=0] Unexpected error from /172.21.0.1; closing
connection (org.apache.kafka.common.network.Selector)
kafka_1      | org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger t
han 104857600)
kafka_1      |  at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:105)
kafka_1      |  at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:448)
kafka_1      |  at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:398)
kafka_1      |  at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:678)
kafka_1      |  at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:580)
kafka_1      |  at org.apache.kafka.common.network.Selector.poll(Selector.java:485)
kafka_1      |  at kafka.network.Processor.poll(SocketServer.scala:861)
kafka_1      |  at kafka.network.Processor.run(SocketServer.scala:760)
kafka_1      |  at java.base/java.lang.Thread.run(Thread.java:834)
`
The config/server.properties file has:
```
 \# The send buffer (SO_SNDBUF) used by the socket server
socket.send.buffer.bytes=102400

\# The receive buffer (SO_RCVBUF) used by the socket server
socket.receive.buffer.bytes=102400

\# The maximum size of a request that the socket server will accept (protection against OOM)
socket.request.max.bytes=104857600 
```

**Comment by cescoffier** [comment]
I don't understand. Are you trying to connect kafka using HTTP? On the port 9092?

**Comment by kbntk** [comment]
@cescoffier Yes, this is what I'm trying to do.

**Comment by cescoffier** [comment]
But that cannot work. Kafka does not use http as protocol. You need a kafka client.

**Comment by kbntk** [comment]
OK. Good to know. Thanks for sharing it with me and thus solving the issue.

**Comment by kbntk** [comment]
What about this example and the part:
`curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"title":"The Shawshank Redemption","year":1994}' \
  http://localhost:8080/movies`
  ?
  
  For this I get the exeption:
  `org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1347375956 larger than 104857600)`

**Comment by kbntk** [comment]
@cescoffier what about the link I shared in previous comment:
[https://quarkus.io/blog/kafka-avro/](https://quarkus.io/blog/kafka-avro/)

That's where I have problems.

**Comment by cescoffier** [comment]
I just tried it, and everything works out of the box.
Of course, that code is 2 years old, and we have simplified a lot in the meantime, but if you do:

> docker-compose up -d
> ./mvnw quarkus:dev # do not use mvn it will not found the avro classes

and in another terminal

> curl --header "Content-Type: application/json" \
  --request POST \
  --data '{"title":"The Shawshank Redemption","year":1994}' \
  http://localhost:8080/movies
  
You get the expected outcome. 

If you believe something is wrong, please provide a reproducer that reproduces the issue. The code you linked works flawlessly.
