### ISSUE TITLE
PKCE flow does not work with Okta

### ISSUE THREAD

**Issue by jie-huang** [quarkusio/quarkus-quickstarts#1106]
1. After setting test account in Okta, I tried use 
samples-nodejs-express-4/resource-server  (as server side) and samples-js-vue/okta-hosted-login (as spa side), it works. So the configuration should be correct.
2. I replaced samples-nodejs-express-4/resource-server with quarkus web
    implementation 'io.quarkus:quarkus-resteasy-reactive-jackson'
    implementation 'io.quarkus:quarkus-oidc'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
And with properties
    quarkus.oidc.application-type=web-app
    quarkus.http.cors=true
    quarkus.http.cors.origins=*
    quarkus.oidc.application-type=web-app
    quarkus.oidc.authentication.pkce-required=true
But, it does not work.
After comparison the req/resp,  I found below differences.
The failed one always tried to redirect Okta after getting request with Bearer token. The client id config is correct too.

Any config I missed for the PKCE flow?
Thanks

**Comment by sberyozkin** [comment]
@jie-huang 

> After comparison the req/resp, I found below differences.
> The failed one always tried to redirect Okta after getting request with Bearer token. The client id config is correct too.

Sorry, may be I got confused. Do you mean you sent a bearer token to Quarkus - but in this case the PKCE is already irrelevant, if it was done then it was completed in your SPA - it is only required to protect a `code` while it is being exchanged for the tokens. `quarkus.oidc.application-type=web-app` is needed when Quarkus itself drives the user authentication. You probably need a `quarkus.oidc.application-type=service`

**Comment by jie-huang** [comment]
After I removed quarkus.oidc.credentials.secret, it works now.
Thanks for your help.
