### ISSUE TITLE
RestAssured configuration for v0.12.0 changes

### ISSUE THREAD

**Issue by kameshsampath** [quarkusio/quarkus-quickstarts#111]
https://github.com/quarkusio/quarkus/issues/1627, the test cases of all the quick starts needs to be updated with `RestAssured.baseURI` setting

**Comment by cescoffier** [comment]
I believe it was a configuration issue? Can we close it?

**Comment by kameshsampath** [comment]
Yes @cescoffier. Since you will have another PR to track test case

**Comment by kameshsampath** [comment]
Thank you
