### ISSUE TITLE
WebAuthn  - Sample code has incorrect URLS in html

### ISSUE THREAD

**Issue by tmulle** [quarkusio/quarkus-quickstarts#1113]
Just downloaded the git source and tried to run the files straight away and received 404 when trying to access any **webauthn** link.

The code has **/webauthn/** and the correct URL should be **/q/webauthn/**

**Comment by hakdogan** [comment]
In addition, you are getting an `undefined` error in Safari.

Safari version: 14.0 (15610.1.28.1.9, 15610)

<img width="1552" alt="Screen Shot 2022-05-15 at 16 57 00" src="https://user-images.githubusercontent.com/657846/168476659-1589e764-b9ce-4a21-b77d-09ee98e3a489.png">

<img width="1552" alt="Screen Shot 2022-05-15 at 16 57 09" src="https://user-images.githubusercontent.com/657846/168476670-84353333-4c22-4388-a77a-ba9e06d8a199.png">

**Comment by FroMage** [comment]
Should be fixed by #1119 

Oh, it passes CI because the test doesn't use the index page, it doesn't emulate browsers and goes straight for the REST endpoints. OK.
