### ISSUE TITLE
A problem when i try to run oc

### ISSUE THREAD

**Issue by alonsoir** [quarkusio/quarkus-quickstarts#116]
Following steps from [official link](https://quarkus.io/guides/kubernetes-guide.html), an error happened. I am trying to push to openshift.

`~/quarkus-apps> oc new-build --binary --name=quarkus-quickstart -l app=quarkus-quickstart
    * A Docker build using binary input will be created
      * The resulting image will be pushed to image stream "quarkus-quickstart:latest"
      * A binary build was created, use 'start-build --from-dir' to trigger a new build

--> Creating resources with label app=quarkus-quickstart ...
    error: the server could not find the requested resource (post imagestreams)
    error: the server could not find the requested resource (post buildconfigs)
--> Failed
`

`~/quarkus-apps> oc status -v
In project default on server https://192.168.99.101:8443

svc/kubernetes - 10.96.0.1:443 -> 8443

svc/quarkus-quickstart (all nodes):31220 -> 8080
  pod/quarkus-quickstart-7cc745ddd7-j6hvz runs quarkus-quickstart/quickstart:latest

Warnings:
  * Unable to list imagestreams resources.  Not all status relationships can be established.
  * Unable to list deploymentconfigs resources.  Not all status relationships can be established.
  * Unable to list routes resources.  Not all status relationships can be established.

Info:
  * pod/quarkus-quickstart-7cc745ddd7-j6hvz has no liveness probe to verify pods are still running.
    try: oc set probe pod/quarkus-quickstart-7cc745ddd7-j6hvz --liveness ...

View details with 'oc describe <resource>/<name>' or list everything with 'oc get all'.
`

` ~/quarkus-apps> oc get all
the server doesn't have a resource type "buildconfigs"
`

**Comment by cescoffier** [comment]
How did you run OpenShift?

**Comment by alonsoir** [comment]
Ok, i can't login with my home user. I will check with IT guys to run with the adequate user/pass.
