### ISSUE TITLE
Failing Quickstarts after Hibernate 6 merge into Quarkus main

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus-quickstarts#1244]
Failing Quickstarts after Hibernate 6 merge into Quarkus main

Failing QS:
 - hibernate-orm-panache-quickstart
 - hibernate-orm-panache-kotlin-quickstart
 - hibernate-search-orm-elasticsearch-quickstart
 - quartz-quickstart

/cc @Sanne @beikov

**Comment by Sanne** [comment]
Thanks for the ping and the list @rsvoboda !
Should be solved by https://github.com/quarkusio/quarkus-quickstarts/pull/1245
