### ISSUE TITLE
Version Bump ignores getting-started/build.gradle

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus-quickstarts#136]
I just noticed that the 8af8b36ee17a9d396369b99505638029e9a55fa7 _[RELEASE] - Bump version to 0.13.0_ which @gsmet and @cescoffier did earlier today missed to bump the version from 0.12.0 to 0.13.0 in quarkus-quickstarts/getting-started/build.gradle 

I've raise PR #137 to manually fix it, but perhaps on the next bump whatever script is (presumably) used to do the release could be adjusted to do it automatically?

@stalep FYI

**Comment by cescoffier** [comment]
This has been fixed.
