### ISSUE TITLE
The guide of "Using Eclipse Vert.x API from a Quarkus Application" did't updated to the latest version?

### ISSUE THREAD

**Issue by startcodeing** [quarkusio/quarkus-quickstarts#1432]
i want to fllow the guide of "Using Eclipse Vert.x API from a Quarkus Application" to write a demo,i don't  found the method onItem() in the blow picture,i got the latest version of quarkus,
![1719922091310](https://github.com/quarkusio/quarkus-quickstarts/assets/11539232/258548e6-0a08-4dff-8f74-a425948aef97)

**Comment by geoand** [comment]
cc @cescoffier @jponge

**Comment by cescoffier** [comment]
Can you tell me the fully qualified name of the Vert.x class?

**Comment by jponge** [comment]
I guess the issue is using `io.vertx.core.Vertx` and not `io.vertx.mutiny.core.Vertx`.

I've checked and the `readFile` method in the Mutiny bindings does return a `Uni<Buffer>`.

**Comment by startcodeing** [comment]
@jponge i think you are right,i shoud use **io.vertx.mutiny.core.Vertx** instead of **io.vertx.core.Vertx**,sorry for trouble you guys
