### ISSUE TITLE
getting-started requires docker 

### ISSUE THREAD

**Issue by franz1981** [quarkusio/quarkus-quickstarts#1433]
84b904c48d28ea6586075b409c4fbf0edefed2da has changed the docker configuration for config-quicktart, but getting-started, nope.

Our perf CI depends by setting correctly the container JVM args to constrain the application (in term of heap capacity) - so it would be great to have getting.started updated or, given that we use a single script to benchmark both applying the same JVM configuration, we will have just one of the the 2 tests to work.

**Comment by franz1981** [comment]
@gsmet

**Comment by gsmet** [comment]
Fixed in the release scripts and in `main` and `development`.

https://github.com/quarkusio/quarkus-release/pull/42

**Comment by franz1981** [comment]
Many thanks @gsmet !!!
