### ISSUE TITLE
camel-java quickstart has no test coverage

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus-quickstarts#146]
camel-java quickstart has no test coverage

**Comment by ppalaga** [comment]
@rsvoboda I could eventually try to fix this. Could you please point me at a quickstart whose tests are especially worth to be used as an inspiration?

**Comment by ppalaga** [comment]
@rsvoboda unping. I see that all other quickstarts' tests look the same, mostly testing over HTTP. The problem with this camel quickstart is that it does not expose any endpoint. It is just a timer based loop writing something to the log. Let me figure out if there is a way to access the log from a test.
