### ISSUE TITLE
infinispan-client quickstart can't run using docker - server case

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus-quickstarts#148]
infinispan-client quickstart can't run using docker (both client and server cases)

Instructions in README suggest to run ISPN server in docker or on the main system.
Running server in docker causes stuck client application, I had to `kill -9` it.
I think it's because of the docker nature where the server is on different network than client.

Errors from client when running against ISPN server in docker:
```
2019-04-12 09:08:19,549 INFO  [org.inf.cli.hot.imp.tra.net.ChannelFactory] (HotRod-client-async-pool-0)
   ISPN004014: New server added(172.17.0.3:11222), adding to the pool.
2019-04-12 09:08:19,549 INFO  [org.inf.cli.hot.imp.tra.net.ChannelFactory] (HotRod-client-async-pool-0)
   ISPN004016: Server not in cluster anymore(localhost:11222), removing from the pool.
2019-04-12 09:09:19,548

  WARN  [org.inf.cli.hot.imp.tra.net.ChannelFactory] (HotRod-client-async-pool-1)
  ISPN004015: Failed adding new server 172.17.0.3:11222: io.netty.channel.ConnectTimeoutException:
  connection timed out: /172.17.0.3:11222
```

**Comment by rsvoboda** [comment]
@karesti / @wburns if you could take a look ...

**Comment by cescoffier** [comment]
it is because of the discovery or the connection to the server?

**Comment by rsvoboda** [comment]
I think so.

**Comment by karesti** [comment]
@rsvoboda which version of infinispan are you using ? are you using docker for mac ?

**Comment by karesti** [comment]
@cescoffier could you please assign the issue to me?

**Comment by rsvoboda** [comment]
Docker for macOS, I will try the workaround

**Comment by rsvoboda** [comment]
Workaround works, comment added to the PR about making it default for better user experience.
PR handles docker issue for server side.

I think I will refocus this issue just for server in docker and create new one for case when client app runs in docker container and ends up with Connection refused: localhost/127.0.0.1:11222. WDYT ?

**Comment by karesti** [comment]
That sounds perfect to me @rsvoboda

**Comment by karesti** [comment]
This one is done too
