### ISSUE TITLE
infinispan-client quickstart - client application in docker  

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus-quickstarts#159]
Currently infinispan-client quickstart support docker instance for infinispan server side.

When client app runs in docker container, it ends up with Connection refused: localhost/127.0.0.1:11222 as it can't see infinispan server inside docker container instance.

I think the solution could be to have docker-compose script which would handle network aspect or add instructions for docker network for ispn client and ispn server instances.

Follow-up for https://github.com/quarkusio/quarkus-quickstarts/issues/148

**Comment by cescoffier** [comment]
@karesti Any idea?

**Comment by karesti** [comment]
This is done

**Comment by karesti** [comment]
https://github.com/quarkusio/quarkus-quickstarts/commit/9129b3c796edc6e0c8cbce3b682838fcee8faf8c

**Comment by karesti** [comment]
is it normal this issue to be still open? @cescoffier @rsvoboda

**Comment by karesti** [comment]
this issue is already fixed
