### ISSUE TITLE
Create a quickstart using MQTT

### ISSUE THREAD

**Issue by misl** [quarkusio/quarkus-quickstarts#197]
There is quickstart for Kafka. A similar quickstart of MQTT will help people (like myself) get started with Quarkus and MQTT.

**Comment by misl** [comment]
I have already started on taking the Kafka quickstart as an example for a MQTT quickstart. Pull request is coming.

**Comment by jesuino** [comment]
Thanks for your great contribution, I saw your code in development! Do you know if this can be extended to use AWS IoT? Would you suggest some example using AWS IoT?

**Comment by misl** [comment]
Hi jesuino,

Unfortunately I am not familiar with AWS IoT, but probably there are similarities with Google IoT and IBM Watson IoT. Even though it is MQTT, each has there own topic naming convention you have to follow (as a result of there device management). This makes it hard to migrate (vendor lock-in).

Getting back to your question. If AWS IoT is based on MQTT it should work. 
- Just take the quickstart example
- configure it to connect with AWS IoT 
  - set the right credentials 
  - subscribe and public to the right topics (Check topic naming convention with AWS IoT)

and give it a go.

**Comment by misl** [comment]
This issue can closed since the changes were merged

**Comment by jesuino** [comment]
Thanks, @misl was just wondering if you tested it with AWS IoT. Unfortunately yes, I agree with you, they provide a Java API which help us to set certificates on their client...

**Comment by misl** [comment]
So what you are actually looking for is support for certificates? Have a look at [smallrye](https://smallrye.io/) (the library taking care of micro profile messaging for Quarkus). Is seems smallrye's [MqttSource](https://github.com/smallrye/smallrye-reactive-messaging/blob/master/smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttSource.java) does not yet support certificates. However, the underlying Vert.x (have a look at [MqttClientOptions](https://vertx.io/docs/apidocs/io/vertx/mqtt/MqttClientOptions.html)) does seems to have support for certificates. 

So it seems adding support for certificates might not be too complicated. I suggest you create an issue and request support for certificates. I am quite sure they accept pull requests (they already accepted some of mine).

PS. maybe this conversation should be part of a Smallrye messaging issue/ticket.
