### ISSUE TITLE
xcrun required for Native-Image build on MacOS

### ISSUE THREAD

**Issue by douglasawoods** [quarkusio/quarkus-quickstarts#204]
On MacOS(Mojave), when doing the native-image build lab, xcrun was required to be installed on the Mac, which was accomplished via "Xcode-select —install". Once installed, the Native Image build lab completed successfully.
Recommend updating the getting-started lab documentation for "Building Native Image Guide" to note xcrun being required on a Mac to successfully complete this lab.

**Comment by cescoffier** [comment]
The documentation has been updated! Thanks for the feedback.
