### ISSUE TITLE
Error producing native-image on macos

### ISSUE THREAD

**Issue by davecramer** [quarkusio/quarkus-quickstarts#220]
Install latest graalvm
using JDK1.8 on macos
in the getting-started example
mvnw package -P native results in:
Error: Already registered: java.lang.reflect.Method.getDefaultValue()
com.oracle.svm.core.util.UserError$UserException: Already registered: java.lang.reflect.Method.getDefaultValue()

**Comment by cescoffier** [comment]
> On 16 Jun 2019, at 15:07, Dave Cramer <notifications@github.com> wrote:
> 
> Install latest graalvm
> 

Quarkus does not support GraalVM 19 yet. We are actively working on this.

**Comment by davecramer** [comment]
@cescoffier thanks for the quick reply! I think I'll leave this open for others.

**Comment by rsvoboda** [comment]
Quarkus 0.18.0 is out, it supports GraalVM 19.0.2
