### ISSUE TITLE
using-kogito fails with ClassCastException

### ISSUE THREAD

**Issue by jcordes73** [quarkusio/quarkus-quickstarts#247]
When running ./mvn package the following error is displayed:

16:26:38,021 INFO  [org.dro.com.kie.bui.imp.KieRepositoryImpl] KieModule was added: org.drools.modelcompiler.CanonicalKieModule@43df2da4
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.699 s <<< FAILURE! - in org.acme.kogito.PersonProcessTest
[ERROR] testAdult  Time elapsed: 0.013 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: 
TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.kogito.PersonProcessTest]: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kogito.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.ClassCastException: org.drools.modelcompiler.CanonicalInternalKieModule cannot be cast to org.drools.compiler.kie.builder.impl.MemoryKieModule
Caused by: java.lang.RuntimeException: 
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kogito.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.ClassCastException: org.drools.modelcompiler.CanonicalInternalKieModule cannot be cast to org.drools.compiler.kie.builder.impl.MemoryKieModule
Caused by: io.quarkus.builder.BuildException: 
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kogito.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.ClassCastException: org.drools.modelcompiler.CanonicalInternalKieModule cannot be cast to org.drools.compiler.kie.builder.impl.MemoryKieModule
Caused by: java.lang.ClassCastException: org.drools.modelcompiler.CanonicalInternalKieModule cannot be cast to org.drools.compiler.kie.builder.impl.MemoryKieModule

I'm using Graalvm 19.1.1.

**Comment by gsmet** [comment]
Which version of Quarkus does it use? We currently do not support 19.1.1 on the released versions. Only master should work with 19.1.1.

That being said, it doesn't ring a bell so we probably need to check the state of the quickstarts with 19.1.1 and current master.

**Comment by jcordes73** [comment]
According to the pom the quarkus version is 0.19.1 (it was a clone from the current master).

So steps where 

git clone https://github.com/quarkusio/quarkus-quickstarts
cd quarkus-quickstarts/using-kogito/
./mvnw clean compile quarkus:dev
./mvnw package

quarkus:dev was working fine.

**Comment by gsmet** [comment]
and does it work with GraalVM 19.0.2? Or not?

Thanks!

**Comment by jcordes73** [comment]
Retested with GraalVM 19.0.2 and it is failing with an error as well:
17:37:29,582 WARN  [org.dro.com.kie.bui.imp.KieProject] No files found for KieBase defaultKieBase
17:37:29,722 INFO  [org.dro.com.kie.bui.imp.KieRepositoryImpl] KieModule was added: org.drools.modelcompiler.CanonicalKieModule@5ba459b3
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 2.438 s <<< FAILURE! - in org.acme.kogito.PersonProcessTest
[ERROR] testAdult  Time elapsed: 0.01 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: 
TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.kogito.PersonProcessTest]: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kogito.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.ClassCastException: org.drools.modelcompiler.CanonicalInternalKieModule cannot be cast to org.drools.compiler.kie.builder.impl.MemoryKieModule
Caused by: java.lang.RuntimeException: 
io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kogito.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.ClassCastException: org.drools.modelcompiler.CanonicalInternalKieModule cannot be cast to org.drools.compiler.kie.builder.impl.MemoryKieModule
Caused by: io.quarkus.builder.BuildException: 
Build failure: Build failed due to errors
	[error]: Build step io.quarkus.kogito.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.ClassCastException: org.drools.modelcompiler.CanonicalInternalKieModule cannot be cast to org.drools.compiler.kie.builder.impl.MemoryKieModule
Caused by: java.lang.ClassCastException: org.drools.modelcompiler.CanonicalInternalKieModule cannot be cast to org.drools.compiler.kie.builder.impl.MemoryKieModul

**Comment by gsmet** [comment]
Hmmm, that is really weird. I tested the quickstarts before releasing.

I'll recheck it as soon as I can, there's definitely something weird going
on.

**Comment by jcordes73** [comment]
Here some info about the java version:

java -version
openjdk version "1.8.0_191"
OpenJDK Runtime Environment (build 1.8.0_191-b12)
OpenJDK 64-Bit Server VM (build 25.191-b12, mixed mode)

I'm using RHEL 7.6.

**Comment by gsmet** [comment]
It's really related to the combination of:
```
./mvnw clean compile quarkus:dev
./mvnw package
```
if the `package` operation is called without a `clean`. If you add `clean`, it works OK.

I wonder if it's related to https://github.com/quarkusio/quarkus/issues/3288 . @mswiderski @mariofusco , does it ring a bell?

**Comment by jcordes73** [comment]
With ./mvnw clean package it works even with the native mode. I'm just a close follower of documentation.

**Comment by mswiderski** [comment]
@gsmet thanks for adding me to this issue, I will have a look to see why the clean makes such a big difference. Will keep you posted

**Comment by mswiderski** [comment]
@jcordes73 @gsmet just tested this on master which already has a fix for quarkusio/quarkus#3288 and it does work as expected. So yes, it does seem to be related to that.

**Comment by cescoffier** [comment]
Fixed.
