### ISSUE TITLE
Update the OIDC guide to use JsonWebToken

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus-quickstarts#308]
@stuartwdouglas, @cescoffier  Hi Stuart, Clement, I'd like to show `JsonWebToken` instead of the Quarkus specific `SecurityIdentity` in this demo, i.e, showing `SecurityIdentity` is also valuable, but I guess better be shown with other demos, in scope of this demo, given that we should be encouraging the users to use MP JWT Api to access the token info and it already works with what Stuart did earlier, showing `JsonWebToken` will be good IMHO.
I'll do a quick PR a bit later

**Comment by cescoffier** [comment]
I believe we need 2 quickstarts or the 2 approaches covered in the same quickstarts. `SecurityIdentity` is containing the JWT token and much more than this.

**Comment by sberyozkin** [comment]
@cescoffier sounds good, yes, showing two approaches is a good plan, thanks. I wont rush then :-), Pedro will may have more ideas after he completes his adapter review
