### ISSUE TITLE
Fix Elytron-JDBC Quickstart in native mode

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-quickstarts#315]
The current quickstart does not work in native because it starts H2 Server, which is not supported.

We need to update the quickstart in order to:

* use a docker-compose file to start a PostGreSQL database with an init script ([example](https://github.com/quarkusio/quarkus-workshops/blob/master/quarkus-workshop-super-heroes/super-heroes/infrastructure/docker-compose.yaml#L3-L10))
* in the tests, use Test Containers with an init script [doc](https://www.testcontainers.org/modules/databases/#using-an-init-function)

CC @danielpetisme

**Comment by danielpetisme** [comment]
Ah!!!! that's why you use Pg in your todo-app demo application !
Ok it's the same pattern, I'll do ASAP.

**Comment by cescoffier** [comment]
Will be fixed by #341
