### ISSUE TITLE
security-openid-connect-web-authentication-quickstart - test are failing

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus-quickstarts#366]
security-openid-connect-web-authentication-quickstart - test are failing with message `org.opentest4j.AssertionFailedError: expected: <Log in to quarkus> but was: <Welcome to Your Quarkus Application>`

Might be related to https://github.com/quarkusio/quarkus/pull/5315
@stuartwdouglas @pedroigor 

Noticed when did https://github.com/quarkusio/quarkus-quickstarts/pull/365 change to make compilation work again.

**Comment by sberyozkin** [comment]
Hmm, It was passing for me, why it was failing ?

**Comment by stuartwdouglas** [comment]
Because nothing was marked as needing authentication, so once my fixes were merged it stopped asking to log in.
