### ISSUE TITLE
amqp-quickstart  alert 'Disconnected'

### ISSUE THREAD

**Issue by wenfer** [quarkusio/quarkus-quickstarts#371]
all is default config

is something need config in rabbitmq?

create queue or exchanges  or anything else?

env: 
rabbitmq 3.8.1
windows10  x64
jdk8

**Comment by cescoffier** [comment]
RabbitMQ is not supported. Our AMQP support is for AMQP 1.0.
To support RabbitMQ you would need a MicroProfile Reactive Messaging connector for RabbitMQ.

Clement

**Comment by wenfer** [comment]
ok , i got it
