### ISSUE TITLE
 @ConfigProperty fails to map value to l class variable variable

### ISSUE THREAD

**Issue by jdang67** [quarkusio/quarkus-quickstarts#388]
Hi, 

The example using **_@ConfigProperty_**  works.
However, when I using the same technique in another class, then the value always null.  Is this a bug or  I am missing something here?

thanks,

Jdang

``` java
package org.acme.config;
import org.eclipse.microprofile.config.inject.ConfigProperty;
public class MyTest {

    @ConfigProperty(name = "greeting.message")
    String message;
    public String getMessage() {
        return message;
    }
}

**Comment by gsmet** [comment]
The value will only be injected in proper CDI beans.

**Comment by jdang67** [comment]
> The value will only be injected in proper CDI beans.
Thanks for your answer, I'm just switching to java for this project. So what do I need to do to make this work?

Jdang
