### ISSUE TITLE
Infinispan quickstart issues / improvements

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-quickstarts#392]
There are few issues / improvements around the infinispan quickstart:

* it uses `:latest`, the issue with this is that it give various results depending on when you pull the image for the first time. Right now for me, it gave `10.1.0.Beta1`, which is probably very recent, but not stable. 

* the cache create must be improved:

Currently, it uses some XML snippets added at startup:

```
void onStart(@Observes StartupEvent ev) {
      LOGGER.info("Create or get cache named mycache with the default configuration");
      RemoteCache<Object, Object> cache = cacheManager.administration().getOrCreateCache("mycache", new XMLStringConfiguration(String.format(CACHE_CONFIG, "mycache")));
      cache.put("hello", "Hello World, Infinispan is up!");
   }
```

* it seems racey

Once in a while, I get a 204, most probably because the cache does not have the value yet or something else. I also get 500, with the cache not being injected in the resource. These issues happen only in native mode.

**Comment by cescoffier** [comment]
Issues can be reproduced with: https://github.com/quarkusio/quarkus-quickstarts/pull/352

**Comment by cescoffier** [comment]
@karesti  can you have a look?

**Comment by emmanuelbernard** [comment]
Ont he race condition, CC @wburns

**Comment by stephennimmo** [comment]
I think the race condition is actually within the CDI context. The `StartupEvent` can run after the `RemoteCache` beans are attempted to be injected using the `@Remote` annotation, resulting in a WARN from the hotrod client. Example: 

`ISPN004005: Error received from the server: org.infinispan.server.hotrod.CacheNotFoundException: Cache with name 'settlement-data-historical' not found amongst the configured caches`

Ultimately, the work should be to extend the devservices `InfinispanDevServiceProcessor` to consume additional configuration to allow for the creation of caches. Something like: 

`
quarkus.infinispan-client.devservices.caches.cache-name1.template=DIST_SYNC
quarkus.infinispan-client.devservices.caches.cache-name2.template=DIST_SYNC
`

**Comment by karesti** [comment]
This has been already fixed
