### ISSUE TITLE
Can't find quarkus-maven-plugin 1.1.1.Final,when use maven.

### ISSUE THREAD

**Issue by lizhuoxuan** [quarkusio/quarkus-quickstarts#418]
latest version is 1.1.0 in mvnrepository.
![image](https://user-images.githubusercontent.com/19903476/72135470-89185780-33c1-11ea-9869-87df9df8a52f.png)

**Comment by rsvoboda** [comment]
It's probably something on https://mvnrepository.com/artifact/io.quarkus/quarkus-maven-plugin side

I can see it when looking at
https://repo1.maven.org/maven2/io/quarkus/quarkus-maven-plugin/1.1.1.Final/
https://repo.maven.apache.org/maven2/io/quarkus/quarkus-maven-plugin/1.1.1.Final/

@cescoffier / @gsmet fyi
Did 1.1.1.Final have any trouble during the release ?

**Comment by gsmet** [comment]
No, it's just that these websites are not updated right away.

The only way to find them just after a release is to go to the source. It can take several hours/days for these websites to be updated.
