### ISSUE TITLE
Wrong test source folder in security-keycloak-authorization-quickstart

### ISSUE THREAD

**Issue by michael-schnell** [quarkusio/quarkus-quickstarts#498]
The test source folder in the "security-keycloak-authorization-quickstart" is:
`
https://github.com/quarkusio/quarkus-quickstarts/tree/master/security-keycloak-authorization-quickstart/src/test/java/org.acme.keycloak.authorization
`

It should be:
`
https://github.com/quarkusio/quarkus-quickstarts/tree/master/security-keycloak-authorization-quickstart/src/test/java/org/acme/keycloak/authorization
`

**Comment by gsmet** [comment]
I think this has been fixed somehow. Thanks for the report.
