### ISSUE TITLE
Vert.x multi-threaded worker verticles

### ISSUE THREAD

**Issue by davidhervas** [quarkusio/quarkus-quickstarts#500]
Hi,
I'm currently teaching myself how to develop some small REST WebServices with Quarkus.
I have been implementing following guide : [https://quarkus.io/guides/reactive-messaging](url)

I have a task that can be split in several sub-tasks and be performed concurrently, I don't manage to get that working with Quarkus and I seek for help.

I defined a bean/verticle :
```
@ApplicationScoped
public class MySubTask {

  @ConsumeEvent("SubTask")
  public Long manageSubTask(String input) {
    
    // Perform long business operation
    
    return 0L;
  }
}
```

From my REST endpoint method I split my task in 2 subtasks and send 2 messages to the verticle :
```
Future<Long> subTaskFuture01 = Future
        .future(promise -> eventBus.<Long>request("SubTask", "input-01",
            message -> {
              promise.complete(message.result().body());
            }));
    asyncTasks.add(subTaskFuture01);

Future<Long> subTaskFuture02 = Future
        .future(promise -> eventBus.<Long>request("SubTask", "input-02",
            message -> {
              promise.complete(message.result().body());
            }));
    asyncTasks.add(subTaskFuture02);
```

Finally I define a CompositeFuture object in order to wait for both subtasks to be done :
```
CompositeFuture.all(asyncTasks).setHandler(ar -> {
      if (ar.succeeded()) {
        // Both subtasks are done
      }
    });
```

I observe that subtask 1 and subtask 2 are run sequentially by the same class instance and not concurrently.
This is kind of normal bevause of the `@ApplicationScoped` annotation on bean/verticle.

I'm looking for both tasks to be executed concurrently by 2 workers like Vert.x native API allows it.
I think i'm looking in Quarkus for the equivalent of Vert.x native API :
```
DeploymentOptions options = new DeploymentOptions()
  .setWorker(true)
  .setInstances(5) // matches the worker pool size below
  .setWorkerPoolName("the-specific-pool")
  .setWorkerPoolSize(5);
vertx.deployVerticle("com.mycompany.MyOrderProcessorVerticle", options);
```

Did my understanding of Vert.x native API and Vert.x in Quarkus API corrects ?
Can somebody help me ?

Thanks by advance.

**Comment by cescoffier** [comment]
Instead of @ConsumeEvent, just deploy your verticle as you would do in "regular" Vert.x:

```
public void deploy(@Observe StartupEvent event, Vertx vertx) {
   vertx.deployVerticle(....) ;
}
```

**Comment by davidhervas** [comment]
Thanks, you have confirmed my understanding of native Vert.x and Vert.x over Quarkus.
I hope this basic feature of Vert.x will be soon available through @ConsumeEvent or similar quarkus anotations.

**Comment by davidhervas** [comment]
Hi,

I managed to make it work in Quarkus.

This will start 4 instances of class MyVerticle.
Those 4 instances are not "Worker", there are "Event loop".
Those 4 instances will not run concurrently. Each one is waiting for ther same specific message on the event bus. When the event bus fire such specific message, only one of those 4 instances will receive it (one instance which is currently free).
```
@Inject
protected Vertx vertx;
...
void onStart(@Observes StartupEvent ev) {
  DeploymentOptions options = new DeploymentOptions().setWorker(false).setInstances(4);
  vertx.deployVerticle(MyVerticle.class, options);
}
```
The corresponding class MyVerticle which register for the message
```
public class MyVerticle extends AbstractVerticle {
  ...
  @Override
  public void init(Vertx vertx, Context context) {
    super.init(vertx, context);
  }
  ...
  @Override
  public void start(Future<Void> startFuture) {

    vertx.eventBus().<String>consumer("EventBusMsg", message -> {

      // perform business

      message.reply("OK");
    });

    super.start(startFuture);
  }
}
```

This will fire several event bus message and we wait for all tasks to be done
```
@Inject
EventBus eventBus;
...
List<Future> asyncTasks = new ArrayList<Future>();
listOfParams.stream().forEach(param -> {
      Future<Long> taskFuture = Future
          .future(
              promise -> eventBus.<String>request("EventBusMsg", param,
                  message -> {
                    String result = message.result().body();
                    promise.complete(result);
                  }));
      asyncTasks.add(taskFuture);
});

...
CompositeFuture.all(asyncTasks).setHandler(ar -> {
      if (ar.succeeded()) {
        // All tasks are succeeded
      }
});
```
