### ISSUE TITLE
Kafka Quickstart: Test Resource opens Kafka Container twice

### ISSUE THREAD

**Issue by cradloff** [quarkusio/quarkus-quickstarts#517]
The class KafkaResource holds an instance of KafkaContainer. In the start method, another KafkaContainer is started but never closed. In the stop method, the container from the instance is closed instead.

https://github.com/quarkusio/quarkus-quickstarts/blob/ceb711a04d59c5f8a7bbf8e1e7731c23e2d93acd/kafka-quickstart/src/test/java/org/acme/kafka/KafkaResource.java#L16

**Comment by gsmet** [comment]
Thanks for reporting this, I created https://github.com/quarkusio/quarkus-quickstarts/pull/518 .

**Comment by ianpartridge** [comment]
Looks like this can be closed.

**Comment by cescoffier** [comment]
Oh right! We fixed this a long time ago!
