### ISSUE TITLE
vertx-quickstart question

### ISSUE THREAD

**Issue by heike2718** [quarkusio/quarkus-quickstarts#523]
There seems to be something missing in the [vertx-quickstart](https://quarkus.io/guides/vertx) documentation.

The GreetingResource being annotated with  @Produces(MediaType.TEXT_PLAIN) returns a Uni<String> which is mapped to a io.smallrye.mutiny.context.ContextPropagationUniInterceptor-Object.toString() instead of the expected Content ("Hello" or "Lorem ipsum..."). I.e. http://localhost:8080/lorem shows this Object as String but not the content.

Is there missing a mapping library that transforms Uni<String> to String or should the method be changed to return a String instead, but how?

I am looking forward to a hint.

Regars,
Heike.

**Comment by cescoffier** [comment]
Can you check you have the `quarkus-resteasy-mutiny` in your dependencies?

**Comment by heike2718** [comment]
@cescoffier 

OK this was the missing part. Unfortunately I overlooked the hint "requires the quarkus-resteasy-mutiny extension". 

Now it works all fine.

Thanks a lot!

I wil close the issue.
