### ISSUE TITLE
quartz clustering not working

### ISSUE THREAD

**Issue by wjsgzcn** [quarkusio/quarkus-quickstarts#542]
I followed the sample codes of quartz, all works well, but when I deploy two replicas in docker stack, the tasks servers works separately, and add double records into the database table.

It seems the quartz clustering is not configured properly? Or there is something I forgot to write?

**Comment by wjsgzcn** [comment]
I find the solution. 

The sample code of TaskBean missing an important parameter of @Scheduled.

Change to the following line of code and CLEAN your quartz tables:
```java
@Scheduled(identity = "print-time-every-10s", every = "10s")
```
Well, identity is the key of quartz tasks, if you don't define the identity, it will generate a random one, so there is two same task but not one.

**Comment by gsmet** [comment]
Which version of Quarkus were you using? Because the name shouldn't be random started with Quarkus 1.4.1.

**Comment by wjsgzcn** [comment]
At first I use 1.3.2, then I change into 1.4.1 after I find the problem. 

After change to the new version, I found the same problem.

Perhaps because I did not clean my database tables after upgrading to 1.4.1?

**Comment by gsmet** [comment]
Yes, that might explain it. In 1.4.1, it should work without an identity defined.

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus/issues/8661 .
