### ISSUE TITLE
"Quarkus - Creating Your First Application " doesn't work

### ISSUE THREAD

**Issue by xyang5987** [quarkusio/quarkus-quickstarts#551]
I'm new to quarkus and tried to learn the first example on https://quarkus.io/guides/getting-started

After run 
mvn io.quarkus:quarkus-maven-plugin:1.4.1.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=getting-started     -DclassName="org.acme.getting.started.GreetingResource"     -Dpath="/hello"

I got the following error messages:

[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] amqp-quickstart                                                    [jar]
[INFO] cache-quickstart                                                   [jar]
[INFO] config-quickstart                                                  [jar]
[INFO] context-propagation-quickstart                                     [jar]
[INFO] dynamodb-quickstart                                                [jar]
[INFO] getting-started                                                    [jar]
[INFO] getting-started-async                                              [jar]
[INFO] getting-started-reactive                                           [jar]
[INFO] getting-started-reactive-rest                                      [jar]
[INFO] getting-started-knative                                            [jar]
[INFO] getting-started-testing                                            [jar]
[INFO] hibernate-orm-quickstart                                           [jar]
[INFO] hibernate-orm-panache-quickstart                                   [jar]
[INFO] hibernate-search-elasticsearch-quickstart                          [jar]
[INFO] infinispan-client-quickstart                                       [jar]
[INFO] jms-quickstart                                                     [jar]
[INFO] kafka-quickstart                                                   [jar]
[INFO] kafka-streams-quickstart                                           [pom]
[INFO] kafka-streams-quickstart-producer                                  [jar]
[INFO] kafka-streams-quickstart-aggregator                                [jar]
[INFO] optaplanner-quickstart                                             [jar]
[INFO] lifecycle-quickstart                                               [jar]
[INFO] microprofile-fault-tolerance-quickstart                            [jar]
[INFO] microprofile-health-quickstart                                     [jar]
[INFO] microprofile-metrics-quickstart                                    [jar]
[INFO] mongodb-quickstart                                                 [jar]
[INFO] mongodb-panache-quickstart                                         [jar]
[INFO] mqtt-quickstart                                                    [jar]
[INFO] neo4j-quickstart                                                   [jar]
[INFO] openapi-swaggerui-quickstart                                       [jar]
[INFO] opentracing-quickstart                                             [jar]
[INFO] quartz-quickstart                                                  [jar]
[INFO] qute-quickstart                                                    [jar]
[INFO] reactive-routes-quickstart                                         [jar]
[INFO] rest-client-quickstart                                             [jar]
[INFO] rest-client-multipart-quickstart                                   [jar]
[INFO] rest-json-quickstart                                               [jar]
[INFO] scheduler-quickstart                                               [jar]
[INFO] security-jdbc-quickstart                                           [jar]
[INFO] security-jwt-quickstart                                            [jar]
[INFO] security-keycloak-authorization-quickstart                         [jar]
[INFO] security-oauth2-quickstart                                         [jar]
[INFO] security-openid-connect-quickstart                                 [jar]
[INFO] security-openid-connect-web-authentication-quickstart              [jar]
[INFO] security-openid-connect-multi-tenancy-quickstart                   [jar]
[INFO] software-transactional-memory-quickstart                           [jar]
[INFO] spring-di-quickstart                                               [jar]
[INFO] spring-web-quickstart                                              [jar]
[INFO] spring-data-jpa-quickstart                                         [jar]
[INFO] spring-security-quickstart                                         [jar]
[INFO] spring-boot-properties-quickstart                                  [jar]
[INFO] tests-with-coverage-quickstart                                     [jar]
[INFO] tika-quickstart                                                    [jar]
[INFO] validation-quickstart                                              [jar]
[INFO] vertx-quickstart                                                   [jar]
[INFO] websockets-quickstart                                              [jar]
[INFO] quickstart-projects                                                [pom]
[INFO] 
[INFO] -------------< io.quarkus.quickstarts:quickstart-projects >-------------
[INFO] Building quickstart-projects 1.0-SNAPSHOT                         [1/57]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.4.1.Final:create (default-cli) @ quickstart-projects ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for quickstart-projects 1.0-SNAPSHOT:
[INFO] 
[INFO] amqp-quickstart .................................... SKIPPED
[INFO] cache-quickstart ................................... SKIPPED
[INFO] config-quickstart .................................. SKIPPED
[INFO] context-propagation-quickstart ..................... SKIPPED
[INFO] dynamodb-quickstart ................................ SKIPPED
[INFO] getting-started .................................... SKIPPED
[INFO] getting-started-async .............................. SKIPPED
[INFO] getting-started-reactive ........................... SKIPPED
[INFO] getting-started-reactive-rest ...................... SKIPPED
[INFO] getting-started-knative ............................ SKIPPED
[INFO] getting-started-testing ............................ SKIPPED
[INFO] hibernate-orm-quickstart ........................... SKIPPED
[INFO] hibernate-orm-panache-quickstart ................... SKIPPED
[INFO] hibernate-search-elasticsearch-quickstart .......... SKIPPED
[INFO] infinispan-client-quickstart ....................... SKIPPED
[INFO] jms-quickstart ..................................... SKIPPED
[INFO] kafka-quickstart ................................... SKIPPED
[INFO] kafka-streams-quickstart ........................... SKIPPED
[INFO] kafka-streams-quickstart-producer .................. SKIPPED
[INFO] kafka-streams-quickstart-aggregator ................ SKIPPED
[INFO] optaplanner-quickstart ............................. SKIPPED
[INFO] lifecycle-quickstart ............................... SKIPPED
[INFO] microprofile-fault-tolerance-quickstart ............ SKIPPED
[INFO] microprofile-health-quickstart ..................... SKIPPED
[INFO] microprofile-metrics-quickstart .................... SKIPPED
[INFO] mongodb-quickstart ................................. SKIPPED
[INFO] mongodb-panache-quickstart ......................... SKIPPED
[INFO] mqtt-quickstart .................................... SKIPPED
[INFO] neo4j-quickstart ................................... SKIPPED
[INFO] openapi-swaggerui-quickstart ....................... SKIPPED
[INFO] opentracing-quickstart ............................. SKIPPED
[INFO] quartz-quickstart .................................. SKIPPED
[INFO] qute-quickstart .................................... SKIPPED
[INFO] reactive-routes-quickstart ......................... SKIPPED
[INFO] rest-client-quickstart ............................. SKIPPED
[INFO] rest-client-multipart-quickstart ................... SKIPPED
[INFO] rest-json-quickstart ............................... SKIPPED
[INFO] scheduler-quickstart ............................... SKIPPED
[INFO] security-jdbc-quickstart ........................... SKIPPED
[INFO] security-jwt-quickstart ............................ SKIPPED
[INFO] security-keycloak-authorization-quickstart ......... SKIPPED
[INFO] security-oauth2-quickstart ......................... SKIPPED
[INFO] security-openid-connect-quickstart ................. SKIPPED
[INFO] security-openid-connect-web-authentication-quickstart SKIPPED
[INFO] security-openid-connect-multi-tenancy-quickstart ... SKIPPED
[INFO] software-transactional-memory-quickstart ........... SKIPPED
[INFO] spring-di-quickstart ............................... SKIPPED
[INFO] spring-web-quickstart .............................. SKIPPED
[INFO] spring-data-jpa-quickstart ......................... SKIPPED
[INFO] spring-security-quickstart ......................... SKIPPED
[INFO] spring-boot-properties-quickstart .................. SKIPPED
[INFO] tests-with-coverage-quickstart ..................... SKIPPED
[INFO] tika-quickstart .................................... SKIPPED
[INFO] validation-quickstart .............................. SKIPPED
[INFO] vertx-quickstart ................................... SKIPPED
[INFO] websockets-quickstart .............................. SKIPPED
[INFO] quickstart-projects ................................ FAILURE [  1.331 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.968 s
[INFO] Finished at: 2020-05-01T00:57:29-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.4.1.Final:create (default-cli) on project quickstart-projects: Unable to generate the project, the `projectGroupId`, `projectArtifactId` and `projectVersion` parameters are not supported when applied to an existing `pom.xml` file -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :quickstart-projects

After searching online, I couldn't find any solution. 

The following is the my environment of my system.

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/apache-maven
Java version: 1.8.0_242, vendor: Oracle Corporation, runtime: /usr/lib/jvm/graalvm-ce-java8-20.0.0/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.3.0-46-generic", arch: "amd64", family: "unix"

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 25.242-b06-jvmci-20.0-b02, mixed mode)

Thanks for any help.

Xuefeng

**Comment by mikrethor** [comment]
It seems you executed the command in a folder already containing a  Quarkus Maven project (the quarkus quickstarts). 
It should work if you execute the command in a folder not containing anything.

Pay attention to have a Maven version 3.6.3 installed and available on your path.

**Comment by gsmet** [comment]
Exactly, you need to create your project outside of an existing Maven project or it will fail.

**Comment by xyang5987** [comment]
Thanks for reply. However, what I did is a step by step of the method in https://quarkus.io/guides/getting-started#bootstrapping-the-project

**Comment by mikrethor** [comment]
The doc doesn’t indicate to go in the quickstart folder after cloning the repo and it seems that you did that. Anyway, were you able to generate a Quarkus project with the command line? It should work outside the repo.

**Comment by xyang5987** [comment]
I can do everything but just can't follow the doc. It has a git clone(3. Solution) then a maven creation(4. Bootstrapping the project). Anyway, it's a good software.
