### ISSUE TITLE
vertx-quickstart with ssl

### ISSUE THREAD

**Issue by jilani97** [quarkusio/quarkus-quickstarts#552]
Hi 

I am trying to connect to my Postgresql instance on GCP with ssl, but  I keep getting different errors.
Does someone know how to connect with that quickstart vertx client project on quarkus?

I have the client-cert.pem the client-key.pem and server-ca.pem from GCP and I am using it like this:

quarkus.ssl.native=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=$USER
quarkus.datasource.password=$PASS
quarkus.datasource.reactive.url=postgresql://$PUBLIC_IP:5432/postgres?ssl=true&sslmode=verify-ca&sslcert=client-cert.pem&sslkey=client-key.pem&sslrootcert=server-ca.pem
myapp.schema.create=true

But I get this error:
Trust options must be specified under verify-full or verify-ca sslmode
If I change to require I get SSL Handshake error.

The connection works with the psql from commandline, but not from this vertx-quickstart from quarkus.

**Comment by jilani97** [comment]
OK, I did a workaround for this. I removed the injected application.properties by removing the 
@Inject above the Pgpool client. 

Then in the FruitResource.java in the vertx quickstart I added this:

PgConnectOptions options = new PgConnectOptions()
        .setPort(5432)
        .setHost("$POSTGRESIP")
        .setDatabase("postgres")
        .setUser("postgres")
        .setPassword("PASSWORD")
        .setSslMode(SslMode.VERIFY_CA)
        .setPemTrustOptions(new PemTrustOptions().addCertPath("server-ca.pem")
        .addCertPath("client-cert.pem"))
        .setPemKeyCertOptions(new PemKeyCertOptions().addCertPath("client-cert.pem").addKeyPath("client-key.pem"))
        .setSsl(true);

    PoolOptions poolOptions = new PoolOptions()
    .setMaxSize(5);

    
    PgPool client = PgPool.pool(options, poolOptions);

And it worked :) 

@gsmet

**Comment by cescoffier** [comment]
Yes, I’m not sure the url version support all the attributes. 

@tsegismont do you know? Maybe it must be extended.

**Comment by tsegismont** [comment]
@cescoffier an issue has been file on the Vert.x repository. Yet we should investigate if it's possible to have a configuration mechanism that is consistent with JDBC datasources. I'll have a look and keep you informed.

**Comment by tsegismont** [comment]
So it seems the standard (JDBC) datasource config does not have SSL specific params. JDBC connection params should be used instead.

I will send a PR to let users configure SSL options for Postgres and MySQL.

@jilani97 thanks for sharing the workaround
