### ISSUE TITLE
[Question] Support grpc

### ISSUE THREAD

**Issue by liangyuanpeng** [quarkusio/quarkus-quickstarts#579]
Does quarkus support grpc? I didn't find any documentation . 

Many Thanks!

**Comment by liangyuanpeng** [comment]
Update 

I have found 
https://github.com/quarkusio/quarkus/tree/master/extensions/grpc/deployment/src/test

**Comment by rafamqrs** [comment]
Yes, quarkus support grpc, but it is experimental yet as you can add the extension: ./mvnw quarkus:add-extension -Dextensions="io.quarkus:quarkus-grpc"
