### ISSUE TITLE
Kafka Quickstart: move JAX-RS endpoint to root

### ISSUE THREAD

**Issue by ianpartridge** [quarkusio/quarkus-quickstarts#617]
Currently, the JAX-RS endpoint for this demo is at `/prices.html`:

`@Path("/prices")`
https://quarkus.io/guides/kafka#the-price-resource

This means that when a user deploys the demo onto OpenShift and click the "Open URL" link in the Topology view, they see an error:

`RESTEASY003210: Could not find resource for full path: http://my-cluster.example.com/`

This is because there is no endpoint defined at the root of the application.

This creates a slightly confusing user experience.

I would like to suggest that we move the `/prices` endpoint to the root to avoid this problem.

**Comment by ianpartridge** [comment]
CC: @gsmet @cescoffier

**Comment by cescoffier** [comment]
As far as I remember, it's done like this because if you follow the instruction root (`/`) is the static page generated by the project generator. However, I don't mind changing. WDYT @gsmet ?

**Comment by ianpartridge** [comment]
Ah that makes sense. We use this quickstart as a template in the Quarkus Appsody stack: https://github.com/appsody/stacks/tree/master/incubator/quarkus/templates/kafka which won't have the static page. I'd like to keep our template and this quickstart in sync, hence opening this issue :)

**Comment by paulrobinson** [comment]
@ianpartridge I just reviewed https://github.com/appsody/stacks/pull/843 today. So if that's merged, the template will have the static page. Does that change anything relating to this request?

**Comment by ianpartridge** [comment]
Hi Paul, yes it does. If you're happy to add the static page to the Appsody template then we can close this :)

**Comment by paulrobinson** [comment]
Yes, I'm happy with it. I've approved the PR.
