### ISSUE TITLE
microprofile-graphql-quickstart: graphql-ui does not work, antlr version mismatch

### ISSUE THREAD

**Issue by janpfeil** [quarkusio/quarkus-quickstarts#631]
**Issue**
Executing a simple query in graphql-ui gives error message

**Expected behaviour**
graphql-ui should run query

**Reproduction**
running quickstart
`mvn compile quarkus:dev`

Execute query at url http://localhost:8080/graphql-ui/
> query allFilms {
>   allFilms {
>     title
>     director
>     releaseDate
>     episodeID
>   }
> }
> 

> `Variables are invalid JSON: JSON.parse: unexpected character at line 1 column 1 of the JSON data`

Console output

> ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.eclipse.yasson.internal.ReflectionUtils (jar:file:/var/m2/repository/org/eclipse/yasson/1.0.7/yasson-1.0.7.jar!/) to constructor java.util.AbstractMap()
> WARNING: Please consider reporting this to the maintainers of org.eclipse.yasson.internal.ReflectionUtils
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release

Running unit tests give similar error message
`mvn test`
> ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.8[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.125 s - in org.acme.microprofile.graphql.FilmResourceTest

**System environment**
- Branch master, commit ba61c316
- Linux
- graalvm-ce-java11-20.1.0
- Apache Maven 3.6.2

**Comment by jmartisk** [comment]
The message about antlr version mismatch is a known problem and should be resolved, but it doesn't have anything to do with the quickstart failing (you can ignore it for now). Anyway, I can't reproduce your problem with graphql-ui, I pasted in this query

```
query allFilms {
allFilms {
title
director
releaseDate
episodeID
}
}
```

and it returned 
```
{
  "data": {
    "allFilms": [
      {
        "title": "A New Hope",
        "director": "George Lucas",
        "releaseDate": "1977-05-25",
        "episodeID": 4
      },
      {
        "title": "The Empire Strikes Back",
        "director": "George Lucas",
        "releaseDate": "1980-05-21",
        "episodeID": 5
      },
      {
        "title": "Return Of The Jedi",
        "director": "George Lucas",
        "releaseDate": "1983-05-25",
        "episodeID": 6
      }
    ]
  }
}
```

perhaps you pasted something wrong? Given that it complains about syntax...

**Comment by jmartisk** [comment]
Hm, I get the same error message if I put the query into the "query variables" window at the bottom left. Are you sure you're pasting your query in the correct window (upper left)?

**Comment by janpfeil** [comment]
Jan, you're absolutely right and I apologize for my newbie mistakes. I had indeed used the "query variables" input element to run my query. Maybe I wouldn't have run into this failure if the ui had a label for the input and output areas. But I must confess that I didn't read the introductory paragraph entirely. 
For the reference to such noobs like me: paste or input the query in the upper left window below the description and all the good promises of graphql come true.

**Comment by jmartisk** [comment]
No problem, I'm glad the problem is solved! Have fun with GraphQL!
