### ISSUE TITLE
quarkus-hibernate-reactive-panache 分页有没有例子？

### ISSUE THREAD

**Issue by weir2010** [quarkusio/quarkus-quickstarts#735]
对 quarkus-hibernate-reactive-panache 分页 不会用 希望给个例子出来

**Comment by yichengxian** [comment]
你在这里中文怕是没人会回

**Comment by jiayaoO3O** [comment]
reactive和不reactive对于查询的操作都是一样的, 只是返回值变成了Uni<>或者Multi<>而已, 你可以直接使用[这篇教程](https://quarkus.io/guides/hibernate-orm-panache)的基本方法来查询
``` java   
PanacheQuery<Fruit> panacheQuery = Fruit.find("name", "菠萝");
PanacheQuery<Fruit> page = panacheQuery.page(Page.ofSize(2));
Uni<List<Fruit>> list = page.list();
```

**Comment by weir2010** [comment]
@jiayaoO3O   我想实现的是  把list  和 count 包装成一个对象  返回给前端

**Comment by jiayaoO3O** [comment]
@weir2010 那你只能新建一个类, 例如Result, 里面有一个list, 有一个count, 然后返回一个Uni< Result >.
假如你已经拿到了:
`Uni<List<String>> listUni = Uni.createFrom().item(new ArrayList<>());`
使用以下语法即可转换为另一个对象:
```
        Uni<SampleEntity> entityUni = listUni.onItem().transform(list -> {
            SampleEntity sampleEntity = new SampleEntity();
            sampleEntity.list = list;
            sampleEntity.age = 32;
            return sampleEntity;
        });
```
关键的点时.onItem().transform(), 它接收一个lambda表达式, 说明你要怎么操作里面的对象

**Comment by weir2010** [comment]
@jiayaoO3O   大佬  可以加下微信么：weirweiwei

**Comment by jiayaoO3O** [comment]
有啥问题发邮件给我就行了, 微信就算了, 上班摸鱼回答你的问题

**Comment by weir2010** [comment]
@jiayaoO3O  大神有空看看邮件 我真的想知道这里怎么实现的

**Comment by jiayaoO3O** [comment]
我周五邮件回复你了你看看是不是垃圾桶拦截了

**Comment by weir2010** [comment]
`@POST
	@Path("list2")
	public Uni<QueryResultVO<Comments>> list2(@QueryParam("page") Integer page, @QueryParam("rows") Integer rows) {
		Uni<List<Comments>> panacheQuery = Comments.findAll().page(page - 1, rows).list();
		Uni<Long> count = Comments.count();
		return Uni.combine().all().unis(panacheQuery, count).combinedWith(this::computeFightOutcome);
	}

	private QueryResultVO<Comments> computeFightOutcome(List<Comments> list, Long count) {
		QueryResultVO<Comments> pageList = new QueryResultVO<>();
		pageList.resultList = list;
		pageList.totalRecord = count;
		return pageList;
	}`

会报错  ERROR [org.jbo.res.res.i18n] (executor-thread-0) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.IllegalStateException: HR000061: Session is currently connecting to database

**Comment by jiayaoO3O** [comment]
@weir2010 
我看你骨骼精奇, 传授你一套太极拳, 这套拳法我只展示一次, 你细细品味, 自己对比一下我下面的代码和你的代码就可以了.

NotificationTestEntity这个类里面有两个字段, 一个是list, 一个是count.
NotificationRecordEntity这个类代表你数据库里面表对应的entity.

你先把quarkus框架升级到2.6.0.Final, 在代码最外层(Service层或者接口层都可以)加上@ReactiveTransactional注解确保开启了响应式事务.

你可以有三种方法实现这个功能 :
```java
var page = NotificationRecordEntity.<NotificationRecordEntity>find("userId", userId)
                    .page(requestEntity.getPage(), requestEntity.getSize());
            var chain = page.list()
                    .chain(list -> {
                        NotificationTestEntity notificationTestEntity = new NotificationTestEntity();
                        notificationTestEntity.setList(list);
                        return Uni.createFrom()
                                .item(notificationTestEntity);
                    });
            return chain.chain(notificationTestEntity -> page.count()
                    .chain(count -> {
                        notificationTestEntity.setCount(count);
                        return Uni.createFrom()
                                .item(notificationTestEntity);
                    }));
```
或者
```java
        var panacheQuery = NotificationRecordEntity.<NotificationRecordEntity>find("userId", userId);
        var list = panacheQuery.page(requestEntity.getPage(), requestEntity.getSize())
                .list();
        var count = panacheQuery.count();
        return Uni.combine()
                .all()
                .unis(list, count)
                .asTuple()
                .onItem()
                .transform(tuple -> {
                    NotificationTestEntity notificationTestEntity = new NotificationTestEntity();
                    notificationTestEntity.setList(tuple.getItem1());
                    notificationTestEntity.setCount(tuple.getItem2());
                    return notificationTestEntity;
                });
```
或者
```java
        var panacheQuery = NotificationRecordEntity.<NotificationRecordEntity>find("userId", userId);
        var list = panacheQuery.page(requestEntity.getPage(), requestEntity.getSize())
                .list();
        var count = panacheQuery.count();
        return Uni.combine()
                .all()
                .unis(list, count)
                .asTuple()
                .chain(tuple -> {
                    NotificationTestEntity notificationTestEntity = new NotificationTestEntity();
                    notificationTestEntity.setList(tuple.getItem1());
                    notificationTestEntity.setCount(tuple.getItem2());
                    return Uni.createFrom()
                            .item(notificationTestEntity);
                });
```
如果你还是看不懂, 那就继续看, 领悟了为止.

**Comment by weir2010** [comment]
@jiayaoO3O   NotificationRecordEntity  在哪个jar包？

**Comment by weir2010** [comment]
@jiayaoO3O 
`@ReactiveTransactional
    @GET
    @Path("list-page/{pageIndex}/{pageSize}")
    public Uni<PageListDTO> listForPage(@PathParam("pageIndex") Integer pageIndex, @PathParam("pageSize") Integer pageSize) {
    	var page = Comments.findAll().page(pageIndex, pageSize);
        var chain = page.list()
                .chain(list -> {
                	PageListDTO pageListDTO = new PageListDTO();
                	pageListDTO.list = list;
                    return Uni.createFrom()
                            .item(pageListDTO);
                });
        return chain.chain(pageListDTO -> page.count()
                .chain(count -> {
                	pageListDTO.count = count;
                    return Uni.createFrom()
                            .item(pageListDTO);
                }));
    }`

`public class PageListDTO<T> {

	public List<T> list;
	public Long count;
}`



2021-12-25 16:03:52,260 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-3) Request failed: java.lang.IllegalStateException: HR000061: Session is currently connecting to database

报错   是我写的代码不对么  请指教

**Comment by weir2010** [comment]
`@GET
	@Path("list-page2/{pageIndex}/{pageSize}")
	public Uni<PageListDTO<Comments>> listPage2(@PathParam("pageIndex") Integer pageIndex,
			@PathParam("pageSize") Integer pageSize) {
		
		return Panache.withTransaction(() -> {
			PanacheQuery<Comments> findAll = Comments.findAll();
			Uni<Long> count = findAll.count();
			Uni<List<Comments>> list = findAll.page(Page.of(pageIndex, pageSize)).list();
			return Uni.combine().all().unis(count, list).combinedWith((c, l) -> new PageListDTO<Comments>(c, l));
		});
	}`

`
import java.util.List;

public class PageListDTO<T> {

	public List<T> list;
	public Long count;
	public PageListDTO() {
	}
	public PageListDTO(Long count, List<T> list) {
		this.list = list;
		this.count = count;
	}
}`
问题已解决
