### ISSUE TITLE
Can you provide an example for API Gateway Proxy Integration with AWS Lambda 

### ISSUE THREAD

**Issue by davidhua94** [quarkusio/quarkus-quickstarts#823]
We generally use a lambda to write about 10 apis， so API Gateway Proxy Integration is more suitable for us, will you provide similar examples in the future?

**Comment by sberyozkin** [comment]
CC @patriot1burke

**Comment by patriot1burke** [comment]
@davidhua94  Did you see this?

https://quarkus.io/guides/amazon-lambda-http
