### ISSUE TITLE
Token question

### ISSUE THREAD

**Issue by Tin-Nguyen** [quarkusio/quarkus-quickstarts#836]
Hi all,

I'm a newbie in KeyCloak and Quarkus. I'm recently facing with an issue related to the JWT token generated from Web-App that I cannot use it as Bearer Authorization via Postman tool. However the token generated via `POST /auth/realms/tenant-a/protocol/openid-connect/token` endpoint works!

I tried to compare both JWT token and figured out those are different and wondering how I can make the token generated by OIDC in Quarkus application can work via Postman.

Token generated via web-app: 
```
eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjeTNMNFVlUUF1cjNjd1p0ZGMyRS1Hc0s2NzlibkRMdHNMcFUyZDY2ZTBRIn0.eyJleHAiOjE2MTg2NjE4NDgsImlhdCI6MTYxODY2MTU0OCwiYXV0aF90aW1lIjoxNjE4NjYxNTQ4LCJqdGkiOiJhMzc4NjY1Ni0zODA4LTQxZmYtYmNkZi0xZWQ3OTJiOTgzN2UiLCJpc3MiOiJodHRwOi8vYXV0aC50cmlwdWRpb3RlY2guY29tOjMyNjY0L2F1dGgvcmVhbG1zL3RlbmFudC1hIiwiYXVkIjoibG9naW4tc2VydmljZSIsInN1YiI6ImQyMWNmNTE3LWQzYzAtNGNhMi1hZGVkLTY3NGZhZDUyYjNiZSIsInR5cCI6IklEIiwiYXpwIjoibG9naW4tc2VydmljZSIsInNlc3Npb25fc3RhdGUiOiJjYWUwNDljZC1kMjE5LTRmZjgtYjhiNS03YzM4MjZmNzgyMWIiLCJhdF9oYXNoIjoiY3ZPSS02Y1UySVJzLW5aamJzZ1BPQSIsImFjciI6IjEiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJBbGljZSBJbiBDaGFpbnMiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbGljZSIsImdpdmVuX25hbWUiOiJBbGljZSIsImZhbWlseV9uYW1lIjoiSW4gQ2hhaW5zIiwiZW1haWwiOiJhbGljZUB0ZW5hbnQtYS5vcmcifQ.TY3ems40uM31TDVexLA9BNjOPrD7JfEK59zDYWo4rx5k4d5jaBm2BulJSTHNxg2PxisfJNhzwStZZZ9o4rVrtV05Hj68a6nwBVwgmPGKDNSbLbQjIetIdRLfesWoVboKqjcLRIweBPP0KrHYT20spoaKERhfMjNtZmhP6t8Hf_A5bgspZv4PApT54nxGUCUGIrYinioa_JLA9jEPpUP5vD9cZn6Q85eSoq7jOf0wu5pkcYv1IPVuTXepw4CKV8gLWh6eAD_JxjKPkT_00ZopPR3GM6JlJtE7QAw_w3oVJZPjpHb2H9VYE-iwUnl3T-Uvq1YcYI0y9BQlIFjmYScNlQ
```

Token generated via  `POST /auth/realms/tenant-a/protocol/openid-connect/token` endpoint:
```
eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJjeTNMNFVlUUF1cjNjd1p0ZGMyRS1Hc0s2NzlibkRMdHNMcFUyZDY2ZTBRIn0.eyJleHAiOjE2MTg2MDg0MDEsImlhdCI6MTYxODYwODEwMSwianRpIjoiNjVlMThiOTEtMmZiMC00MWIzLWE1Y2EtOGVmMjRmMjZkMTgyIiwiaXNzIjoiaHR0cDovL2F1dGgudHJpcHVkaW90ZWNoLmNvbTozMjY2NC9hdXRoL3JlYWxtcy90ZW5hbnQtYSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiJkMjFjZjUxNy1kM2MwLTRjYTItYWRlZC02NzRmYWQ1MmIzYmUiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJsb2dpbi1zZXJ2aWNlIiwic2Vzc2lvbl9zdGF0ZSI6ImNjOWI1MmQ4LWQ0Y2MtNDdjZi1iMWNmLTdiN2IyNDRmN2UwOCIsImFjciI6IjEiLCJhbGxvd2VkLW9yaWdpbnMiOlsiaHR0cDovL2xvZ2luLWRldi50cmlwdWRpb3RlY2guY29tOjgwODAiXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsIm5hbWUiOiJBbGljZSBJbiBDaGFpbnMiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJhbGljZSIsImdpdmVuX25hbWUiOiJBbGljZSIsImZhbWlseV9uYW1lIjoiSW4gQ2hhaW5zIiwiZW1haWwiOiJhbGljZUB0ZW5hbnQtYS5vcmcifQ.QE0MnPiVjGdtBInlmKVoy1oy6DLTEJnmRICoIPlkrpZsAP_lHFW4UjQNwjWeUKg_ZfqLF2FpwyxU2Ugl00YDPl1Tu2TyPDa7xP-L-D9w_HfmoD83OTDyukWWyZIcTeaOysqfi2a0nxCExRa-jN9GqR3IND9j6pBIsFZMqX8D6JswpPEFHaYcVTH0OuOidTpH0Y6gNHQu0Jm23mpnxraUDwu65qLWb5Aad3T5B3wZ3V7kH3fy0lMmJSMC2GvZUZrcrIipfqHveVfgb7tCEBwefwW-iWpjySY_VjHgwaXyhE6XRdU79VTn80QSUeajbWpd_SXyZW6kcORyTQpnZFnMJQ
```

The reason why I'm trying to do this since I want to leverage the OpenID Connect from [the extension ](https://quarkus.io/guides/security-openid-connect-multitenancy#quarkus-oidc_quarkus.oidc.token.token-type) to make the authentication on my Web Application (SSO Log In), save the token into the cookie and use it for my SPA application.

Any idea always welcome. TIA.

**Comment by sberyozkin** [comment]
@Tin-Nguyen Sorry for a delay - it is better to ask in StackOverflow or Zulip.

The reasons these are different are most likely to do with the fact that the asymmetric key signing process always produces different signatures, if you were to use a secret key it would be the same all the time.

FYI, by default, ID and access tokens are saved as cookies - and they are also injectable into the endpoints:
https://quarkus.io/guides/security-openid-connect-web-authentication#access_id_and_access_tokens

So you can return them to your SPA via a custom payload

HTH
Thanks
