### ISSUE TITLE
Multiple authentication mechanism: Ldap and smallrye jwt

### ISSUE THREAD

**Issue by LinoMDS** [quarkusio/quarkus-quickstarts#840]
I've look at the documentation https://quarkus.io/guides/security-ldap, but in this doc doesn´t explain how to secure only a few endpoints with ldap, is it possible to only have ldap for one endpoint and the rest of the application with smallrye jwt for example? if so, how can I specify the endpoint that this is to be secure with ldap? Also can the ldap be override in order to send the user password from user input instead of reading it from properties?

**Comment by sberyozkin** [comment]
@LinoMDS Sorry for a delay, it is better be asked in StackOverflow or Zulip. 

FYI, this PR, https://github.com/quarkusio/quarkus/pull/16634, will make it possible to restrict the authentication method to specifc paths starting from `2.0.0.Alpha3` - right now all authentication methods apply to all of the endpoint space.
In your case you'd configure that for this and that path `basic` authentication applies - Quarkus LDAP is an `IdentityProvider` which will be used to convert Basic Auth credentials into the security identity.
CC @stuartwdouglas 
HTH, thanks
