### ISSUE TITLE
Qute quickstart uses @ResourcePath

### ISSUE THREAD

**Issue by rvansa** [quarkusio/quarkus-quickstarts#843]
`@ResourcePath` seems to be deprecated by `@Location`.

**Comment by rvansa** [comment]
CC @mkouba (you seem to be the author of the quickstart)

**Comment by mkouba** [comment]
Hm, I don't see this annotation used in the https://github.com/quarkusio/quarkus-quickstarts/tree/main/qute-quickstart?

**Comment by rvansa** [comment]
I should probably move the issue to github pages repository: it's in the text https://quarkus.io/guides/qute

**Comment by rvansa** [comment]
Created https://github.com/quarkusio/quarkusio.github.io/issues/966
