### ISSUE TITLE
Maven lifecycle 

### ISSUE THREAD

**Issue by dalexandrov** [quarkusio/quarkus-quickstarts#88]
Hi!

I've tried to play with Quarkus but the very first start of getting started project gave me this:
https://gist.github.com/dalexandrov/8a0de7636a177c7fb36eddf93c69ed99

With the command mvn compile qaurkus:dev the project has started.

If the idea is to follow mvn lifecycle may be it will be good idea to stick it to mvn package?

Still the project looks awesome!!

**Comment by cescoffier** [comment]
Can you check the maven version you are using?

**Comment by dalexandrov** [comment]
Oh, it was Idea's bundled 3.3.9. As I switched manually to 3.6.0 it worked like charm!
