### ISSUE TITLE
overwrite DevServices in hibernate-orm-quickstart

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus-quickstarts#883]
Can we overwrite the default DevServices in dev mode?
I was using postgresql, so it tried to start the dev db from container. However, I have my own dev db there and have many prepared data for dev, basically I want to overwrite the db provided by DevServices, any way to do that?

**Comment by cescoffier** [comment]
Dev service is only enabled if you don't configure the data source, so if you configure and it will be disabled.
You can also disable it from the configuration.

**Comment by liuzqt** [comment]
thanks, I've successfully disabled it and now dev will connect to my specified db.
