### ISSUE TITLE
hibernate-orm how is entity registered in the example?

### ISSUE THREAD

**Issue by liuzqt** [quarkusio/quarkus-quickstarts#888]
I was playing around `hibernate-orm-quickstart`, one question to me is that how we register the entity class? It seems that this is done implicitly, but I can not figure out how quarkus do this when bootstrapping hibernate......

My previous experience was using hibernate native bootstrapping by explicitly calling `addAnnotatedClass`, which is quite different from quarkus example.

**Comment by cescoffier** [comment]
Quarkus detects the entity at build time.
