### ISSUE TITLE
quarkus:dev maven target does not support spaces

### ISSUE THREAD

**Issue by eador** [quarkusio/quarkus-quickstarts#94]
If the path where your project lives has a space in it quarkus:dev will fail to start up the application.

For example:
~/te st/quarkus-quickstarts/getting-started . <-- Will not work
~/test/quarkus-quickstarts/getting-started  <-- Will work

**Comment by gsmet** [comment]
@eador I don't think the issue is specific to the quickstarts. Could you report it on the main project? With the error you have.

**Comment by eador** [comment]
Moved issue to main project.
