### ISSUE TITLE
Is there solution to provide Role-Based Access Control to the fields of entity class?

### ISSUE THREAD

**Issue by thanhlai1212** [quarkusio/quarkus-quickstarts#948]
I want to set RBAC to "status" field of Appointment entity in order to "updateAppointment" endpoint only update or return the value of "status" field when user has role "admin":

```
@Column(name = "status")
@Enumerated(EnumType.STRING)
@RolesAllowed('admin')
private AppointmentStatus status = AppointmentStatus.NEW;
```

I understand that @RoleAllowed annotation only support method and type target. So, I don't know how to resolve this?

This is Graphql endpoint:
```
@Mutation
public Appointment updateAppointment(final Appointment appointment) {
     return appointmentService.updateAppointment(appointment);
}
```
  
and Appointment entity class:
```
@Entity
@Getter
@Setter
@Table(name = "appointments")
public class Appointment extends AuditableEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "appointments_seq")
    @SequenceGenerator(name = "appointments_seq", allocationSize = Constants.ALLOCATION_SIZE)
    private Long id;

    @Column(name = "date")
    private LocalDate date;

    @Column(name = "start_time")
    private LocalTime startTime;

    @Column(name = "end_time")
    private LocalTime endTime;

    @Column(name = "status")
    @Enumerated(EnumType.STRING)
    private AppointmentStatus status = AppointmentStatus.NEW;
}
```

Thank you for your support.

**Comment by thanhlai1212** [comment]
@gsmet @geoand
Sorry for interrupt. Please give me some advices. Thank you.

**Comment by thanhlai1212** [comment]
This has been dicussed and will be fixed at https://github.com/smallrye/smallrye-graphql/issues/960

**Comment by phillip-kruger** [comment]
You can (for now) use a @Source field the achieve this.

So add the `@Ignore` on the `AppointmentStatus` field in `Appointment` and add a method in your endpoint that takes a `@Source Appointment appointment` parameter that then return the field value. And the ass `RolesAllowed` on that method.

It's a hack, but at least a workaround
