### ISSUE TITLE
security-keycloak-authorization-quickstart Guide and application.properties should be updated to https

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus-quickstarts#972]
in [ https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-keycloak-authorization-quickstart/src/main/resources/application.properties ]

we have this line

quarkus.oidc.auth-server-url=https://localhost:8543/auth/realms/quarkus

but in [ https://github.com/quarkusio/quarkus-quickstarts/blob/main/security-keycloak-authorization-quickstart/README.md ]

we use the port : 8180    
http://localhost:8180/auth/realms/quarkus/protocol/openid-connect/token

I checked the git history and I did a rollback and the sample in running now.

quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/quarkus

---------
from Sergey

I recall now it was done to test keycloak authorization can work over HTTPS with the TLS verification disabled, there is a problem with using the Keycloak Admin Client with HTTPS so I could not test the Quarkus/main.
Does it work for you if, with the https: address, if you also add `quarkus.oidc.tls.verification=none` (as in the quickstart properties) ?
IMHO it would make sense to update the guide itself to show `https:` can be used...

**Comment by sberyozkin** [comment]
this issue has been resolved with https://github.com/quarkusio/quarkus-quickstarts/pull/973, thanks @survivant
