### ISSUE TITLE
[GraalVM 21.3.0.r17] PostGres Native Issue

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-quickstarts#988]
All the quickstarts using the JDBC PostgreSQL driver do not work with the Java 17 support of GraalVM 21.3.0:

```
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: sun.security.krb5.Credentials.
```

Impacted quickstarts:

* context-propagation-quickstart
* hibernate-orm-multi-tenancy-quickstart
* hibernate-orm-panache-quickstart
* hibernate-orm-quickstart
* hibernate-search-orm-elasticsearch-quickstart
* security-jdbc-quickstart
* security-jpa-quickstart
* spring-data-jpa-quickstart

To reproduce, take any of these quickstarts and install GraalVM 21.3.0.r17. Then just build the quickstart with: `mvn verify -Pnative`

**Comment by Sanne** [comment]
The core issue is https://github.com/quarkusio/quarkus/issues/21359

Just sent a PR to fix it.

**Comment by n1hility** [comment]
@cescoffier can we close the fix was merged?

**Comment by cescoffier** [comment]
Yes, everything got fixed. So we can close it.
