### ISSUE TITLE
[GraalVM 21.3.0.r17] Kogito quickstarts build failure with Java 17

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus-quickstarts#991]
When using the Java 17 support of GraalVM 21.3.0, multiple Kogito quickstarts fail:

* kogito-drl-quickstart -  Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: sun.management.Util.
* kogito-pmml-quickstart - com.oracle.svm.core.util.UserError$UserException: No instances of java.io.FilePermission are allowed in the image heap as this class should be initialized at image runtime. To see how this object got instantiated use --trace-object-instantiation=java.io.FilePermission.
* kogito-quickstart - Test failure (JVM mode)

**Comment by jerboaa** [comment]
@cescoffier Could you please provide exact steps how to reproduce the `kogito-drl-quickstart`and `kogito-pmml-quickstart` issues?

**Comment by cescoffier** [comment]
I just ran mvn verify -Pnative with GRAALVM_HOME pointing to a java 17 graalvm/mandrel.

BTW, these issues may have been fixed.

**Comment by jerboaa** [comment]
> I just ran mvn verify -Pnative with GRAALVM_HOME pointing to a java 17 graalvm/mandrel.

OK, thanks. I just did and it didn't reproduce.
 
> BTW, these issues may have been fixed.

It looks like to me from where I'm standing. So perhaps this issue needs closing? Tried with 21.3.1 JDK 17 mandrel release.

**Comment by cescoffier** [comment]
Yes, I just verified it. Seems to work as expected now!.
